### ISSUE TITLE
Fix : Improve Navbar Design in Mobile View

### ISSUE THREAD

**Issue by Fahdlabba** [Google-Developer-Student-Clubs-ISSATSo/Hackwarts-2.0#20]
## Description
The navbar section in the mobile view is not user-friendly and needs an update to improve usability and aesthetics. 
Due to its layout and design, users may experience difficulties navigating or interacting with the menu.

---

### Current Behavior
- Navbar elements are too close together, making them hard to tap.

### Expected Behavior
- Navbar elements should have enough spacing for easy interaction.
- Styling should maintain consistency with the desktop view but be optimized for mobile.

### Proposed Solution
1. Maybe we can omit the text and only display the Login/Register icon.

---

### Environment Details
- **Browser:** [e.g., Chrome, Safari]
- **Device:** [e.g., iPhone 12, Samsung Galaxy S21]
- **Screen Size:** [e.g., 375x812 pixels]

---

### Attachments
- Screenshots of the current navbar in mobile view.

![Screenshot from 2024-12-08 21-41-55](https://github.com/user-attachments/assets/2485a325-3307-48e7-92be-f5004857e673)

**Comment by JustPowerful** [comment]
@Fahdlabba Instead of omitting the text we can hide the buttons and display a navbar menu i'll work on it rn
